# Jekyll configuration
plugins:
  - jekyll-paginate

name: grimmer-std
description: Blog o CTFach oraz grach wojennych.

# Url is currently only used only for the RSS feed in feed.xml
url: https://grimmer-std.github.io
#url: http://localhost:4000

# For a project page here should be a project name. Otherwise (for user's/organization's page leave it empty)
baseurl:

author: Grimmer
theme_author: Pavel Makhov
copyright: 2020

share:
  facebook: false
  twitter: true
  gplus: false
  linkedin: false
  pinterest: false
  email: true

social:
  github: grimmer-std
  twitter: grimmer_std
  stackoverflow:
  linkedin:
  instagram: 
  lastfm: 
  rss: feed.xml

# Google Analytics key, leave blank to ignore
google_analytics_key: UA-167092667-1

# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: grimmer-std
comments: true

permalink: /:year/:month/:title/

# Enable for using pages, more details are here: http://jekyllrb.com/docs/pagination/
paginate: 6

#highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: true


exclude: ['README.md', 'LICENSE']
